import test from 'node:test'
import assert from 'node:assert/strict'
import { Store } from './store.mjs'
const doc = () => ({ type: 'doc', content: [
  { type: 'paragraph', attrs: { id: 'a' }, content: [{ type: 'text', text: 'Original' }] },
  { type: 'bulletList', attrs: { id: 'list' }, content: [{ type: 'listItem', attrs: { id: 'li' }, content: [{ type: 'paragraph', attrs: { id: 'nested' }, content: [{ type: 'text', text: 'Nested' }] }] }] },
  { type: 'paragraph', attrs: { id: 'b' }, content: [{ type: 'text', text: 'Other' }] },
] })
function setup() {
  const store = new Store()
  store.sync({ json: doc(), markdown: 'Original\n\nOther', title: 'Test', expectedRevision: 0 })
  const job = store.enqueue({ instruction: 'Improve paragraph', sessionId: 's', blockIds: ['a'] })
  store.claim(job.id, 's')
  const block = job.snapshot.blocks[0]
  const proposal = store.propose({ jobId: job.id, blockId: 'a', blockRevision: block.revision, before: 'Original', after: 'Improved', explanation: 'Clearer' }, 's')
  return { store, job, proposal }
}
test('accept preserves unrelated writing', () => {
  const { store, proposal } = setup()
  const next = doc(); next.content[2].content[0].text = 'User keeps typing'
  store.sync({ json: next, expectedRevision: 1 })
  const result = store.review(proposal.id, 'accept')
  assert.equal(result.document.json.content[0].content[0].text, 'Improved')
  assert.equal(result.document.json.content[2].content[0].text, 'User keeps typing')
})
test('writer can edit the proposed text before accepting', () => {
  const { store, proposal } = setup()
  store.review(proposal.id, 'accept', { text: 'Improved by the writer' })
  assert.equal(store.snapshot().blocks[0].text, 'Improved by the writer')
  assert.equal(proposal.finalText, 'Improved by the writer')
})
test('changed target is stale and never overwritten', () => {
  const { store, proposal } = setup()
  const next = doc(); next.content[0].content[0].text = 'Writer rewrite'
  store.sync({ json: next, expectedRevision: 1 })
  assert.equal(store.view().proposals[0].stale, true)
  assert.equal(store.review(proposal.id, 'accept').stale, true)
  assert.equal(store.snapshot().blocks[0].text, 'Writer rewrite')
})
test('deleted target is stale', () => {
  const { store, proposal } = setup(); const next = doc(); next.content.shift()
  store.sync({ json: next, expectedRevision: 1 })
  assert.equal(store.review(proposal.id, 'accept').stale, true)
})
test('session ownership is enforced', () => {
  const { store, job } = setup()
  assert.throws(() => store.claim(job.id, 'other'))
  assert.throws(() => store.propose({ jobId: job.id, blockId: 'a', blockRevision: 'x', before: 'Original', after: 'Wrong' }, 'other'))
})
test('cancel invalidates proposals, activity and late results', () => {
  const { store, job, proposal } = setup()
  store.activity(job.id, 's', { state: 'writing', progress: 10 })
  store.cancel(job.id)
  assert.throws(() => store.review(proposal.id, 'accept'))
  assert.throws(() => store.propose({ jobId: job.id }, 's'))
  assert.equal(proposal.status, 'cancelled')
  assert.deepEqual(store.view().activity, [])
})
test('reject leaves canonical text intact', () => {
  const { store, proposal } = setup(); store.review(proposal.id, 'reject')
  assert.equal(store.snapshot().blocks[0].text, 'Original')
})
test('duplicate acceptance cannot apply twice', () => {
  const { store, proposal } = setup(); store.review(proposal.id, 'accept')
  assert.throws(() => store.review(proposal.id, 'accept'))
})
test('formatting change invalidates proposal even if text is unchanged', () => {
  const { store, proposal } = setup(); const next = doc(); next.content[0].content[0].marks = [{ type: 'bold' }]
  store.sync({ json: next, expectedRevision: 1 })
  assert.equal(store.review(proposal.id, 'accept').stale, true)
})
test('reconsider queues a follow-up job carrying the note', () => {
  const { store, job, proposal } = setup()
  assert.throws(() => store.review(proposal.id, 'reconsider', { feedback: '  ' }))
  const result = store.review(proposal.id, 'reconsider', { feedback: 'Too formal' })
  assert.equal(proposal.status, 'reconsidered')
  assert.equal(result.job.sessionId, 's')
  assert.deepEqual(result.job.blockIds, ['a'])
  assert.equal(result.job.context.reconsiders, proposal.id)
  assert.match(result.job.instruction, /Too formal/)
  assert.equal(store.claim(result.job.id, 's').context.previous.after, 'Improved')
  assert.notEqual(result.job.id, job.id)
})
test('insert proposals anchor to top-level blocks and accept parsed nodes with fresh ids', () => {
  const store = new Store()
  store.sync({ json: doc(), expectedRevision: 0 })
  const job = store.enqueue({ instruction: 'Add a summary', sessionId: 's', blockIds: [] })
  store.claim(job.id, 's')
  const proposal = store.propose({ jobId: job.id, type: 'insert', anchorBlockId: 'nested', placement: 'after', markdown: 'Summary', explanation: 'Adds context' }, 's')
  assert.equal(proposal.anchorBlockId, 'list', 'nested anchors resolve to their top-level block')
  const result = store.review(proposal.id, 'accept', { nodes: [{ type: 'paragraph', attrs: { id: 'a' }, content: [{ type: 'text', text: 'Summary' }] }, { type: 'heading', attrs: { level: 3 }, content: [{ type: 'text', text: 'H' }] }] })
  const content = result.document.json.content
  assert.equal(content.length, 5)
  assert.equal(content[2].content[0].text, 'Summary')
  assert.notEqual(content[2].attrs.id, 'a', 'colliding ids are replaced')
  assert.ok(content[3].attrs.id)
  assert.deepEqual(proposal.insertedIds, [content[2].attrs.id, content[3].attrs.id])
})
test('insert proposals go stale when the anchor disappears', () => {
  const store = new Store()
  store.sync({ json: doc(), expectedRevision: 0 })
  const job = store.enqueue({ instruction: 'Add', sessionId: 's', blockIds: [] }); store.claim(job.id, 's')
  const proposal = store.propose({ jobId: job.id, type: 'insert', anchorBlockId: 'b', markdown: 'X', explanation: '' }, 's')
  const next = doc(); next.content.pop()
  store.sync({ json: next, expectedRevision: 1 })
  assert.equal(store.review(proposal.id, 'accept', { nodes: [{ type: 'paragraph' }] }).stale, true)
})
test('activity is scoped to snapshot blocks and clamps progress', () => {
  const { store, job } = setup()
  const activity = store.activity(job.id, 's', { blockIds: ['a', 'missing'], state: 'thinking', progress: 140, message: 'x'.repeat(300) })
  assert.deepEqual(activity.blockIds, ['a'])
  assert.equal(activity.progress, 100)
  assert.equal(store.state.activity[job.id].message.length, 200)
  assert.throws(() => store.activity(job.id, 's', { state: 'dancing' }))
})
test('changed proofreading targets supersede jobs and reject late proposals', () => {
  const store = new Store()
  store.sync({ json: doc(), expectedRevision: 0 })
  const job = store.enqueue({ instruction: 'Proofread', sessionId: 's', blockIds: ['a'], kind: 'proofread' })
  store.claim(job.id, 's')
  const next = doc(); next.content[0].content[0].text = 'New draft'
  store.sync({ json: next, expectedRevision: 1 })
  assert.equal(job.status, 'superseded')
  const block = job.snapshot.blocks[0]
  assert.throws(() => store.propose({ jobId: job.id, blockId: block.id, blockRevision: block.revision, before: block.text, after: 'Old result' }, 's'))
})
test('job snapshots remain immutable through accepted edits', () => {
  const { store, job, proposal } = setup()
  store.review(proposal.id, 'accept')
  assert.equal(job.snapshot.blocks[0].text, 'Original')
  assert.equal(job.snapshot.json.content[0].content[0].text, 'Original')
})
test('tables are blocks: markdown round-trips, replace rebuilds rows and cells with ids', () => {
  const store = new Store()
  const table = { type: 'table', attrs: { id: 't' }, content: [
    { type: 'tableRow', attrs: { id: 'r1' }, content: [{ type: 'tableHeader', attrs: { id: 'h1' }, content: [{ type: 'paragraph', attrs: { id: 'hp1' }, content: [{ type: 'text', text: 'Idea' }] }] }, { type: 'tableHeader', attrs: { id: 'h2' }, content: [{ type: 'paragraph', attrs: { id: 'hp2' }, content: [{ type: 'text', text: 'Next' }] }] }] },
    { type: 'tableRow', attrs: { id: 'r2' }, content: [{ type: 'tableCell', attrs: { id: 'c1' }, content: [{ type: 'paragraph', attrs: { id: 'cp1' }, content: [{ type: 'text', text: 'Write' }] }] }, { type: 'tableCell', attrs: { id: 'c2' }, content: [{ type: 'paragraph', attrs: { id: 'cp2' }, content: [{ type: 'text', text: 'Edit' }] }] }] },
  ] }
  store.sync({ json: { type: 'doc', content: [table, { type: 'paragraph', attrs: { id: 'after' }, content: [{ type: 'text', text: 'Tail' }] }] }, expectedRevision: 0 })
  const block = store.snapshot().blocks.find(b => b.id === 't')
  assert.equal(block.type, 'table')
  assert.equal(block.text, '| Idea | Next |\n| --- | --- |\n| Write | Edit |')
  assert.equal(block.plain, true)
  const job = store.enqueue({ instruction: 'Fix table', sessionId: 's', blockIds: ['t'] }); store.claim(job.id, 's')
  assert.throws(() => store.propose({ jobId: job.id, blockId: 't', blockRevision: block.revision, before: block.text, after: 'not a table' }, 's'))
  const proposal = store.propose({ jobId: job.id, blockId: 't', blockRevision: block.revision, before: block.text, after: '| Idea | Next step | Owner |\n| --- | --- | --- |\n| Write freely | Edit later | You |\n| Review | Accept | Claude |', explanation: 'adds a column and a row' }, 's')
  assert.equal(proposal.blockType, 'table')
  const result = store.review(proposal.id, 'accept')
  const rebuilt = result.document.json.content[0]
  assert.equal(rebuilt.attrs.id, 't')
  assert.equal(rebuilt.content.length, 3)
  assert.equal(rebuilt.content[0].content[0].type, 'tableHeader')
  assert.equal(rebuilt.content[0].content[2].content[0].content[0].text, 'Owner')
  assert.equal(rebuilt.content[0].content[0].attrs.id, 'h1', 'existing cells keep their ids')
  assert.ok(rebuilt.content[2].attrs.id && rebuilt.content[2].attrs.id !== 'r2', 'new rows get fresh ids')
  assert.equal(result.node.attrs.id, 't')
  assert.equal(store.snapshot().blocks.find(b => b.id === 't').text.split('\n').length, 4)
  assert.equal(result.document.json.content[1].content[0].text, 'Tail')
})
test('formatted blocks round-trip as inline markdown and accept styled content', () => {
  const store = new Store()
  const json = { type: 'doc', content: [{ type: 'paragraph', attrs: { id: 'f' }, content: [{ type: 'text', text: 'Leftovers', marks: [{ type: 'bold' }] }, { type: 'text', text: ' remain after ' }, { type: 'text', text: 'cleanup', marks: [{ type: 'link', attrs: { href: 'https://example.com' } }] }, { type: 'text', text: '.' }] }] }
  store.sync({ json, expectedRevision: 0 })
  const block = store.snapshot().blocks[0]
  assert.equal(block.text, '**Leftovers** remain after [cleanup](https://example.com).')
  assert.equal(block.plain, false)
  const job = store.enqueue({ instruction: 'Better word', sessionId: 's', blockIds: ['f'] }); store.claim(job.id, 's')
  const proposal = store.propose({ jobId: job.id, blockId: 'f', blockRevision: block.revision, before: block.text, after: '**Remnants** remain after cleanup.', explanation: 'word' }, 's')
  const result = store.review(proposal.id, 'accept', { text: proposal.after, content: [{ type: 'text', text: 'Remnants', marks: [{ type: 'bold' }, { type: 'evil' }] }, { type: 'text', text: ' remain after cleanup.' }] })
  const content = result.document.json.content[0].content
  assert.deepEqual(content[0], { type: 'text', text: 'Remnants', marks: [{ type: 'bold' }] })
  assert.equal(store.snapshot().blocks[0].text, '**Remnants** remain after cleanup.')
})
test('an empty replacement removes the block', () => {
  const store = new Store()
  store.sync({ json: doc(), expectedRevision: 0 })
  const job = store.enqueue({ instruction: 'Delete', sessionId: 's', blockIds: ['a'] }); store.claim(job.id, 's')
  const block = job.snapshot.blocks.find(b => b.id === 'a')
  const proposal = store.propose({ jobId: job.id, blockId: 'a', blockRevision: block.revision, before: block.text, after: '', explanation: 'redundant' }, 's')
  const result = store.review(proposal.id, 'accept')
  assert.equal(result.removed, true)
  assert.equal(result.document.json.content.some(n => n.attrs?.id === 'a'), false)
  assert.equal(result.document.json.content[0].attrs.id, 'list')
})
test('comments attach to a block and replies queue a follow-up job', () => {
  const { store, job } = setup()
  const comment = store.propose({ jobId: job.id, type: 'comment', blockId: 'a', text: 'This claim needs a **source**.' }, 's')
  assert.equal(comment.type, 'comment')
  assert.equal(store.view().proposals.find(p => p.id === comment.id).stale, false)
  assert.throws(() => store.review(comment.id, 'reconsider', { feedback: 'x' }))
  const replied = store.review(comment.id, 'reply', { feedback: 'Use the 2019 paper.' })
  assert.equal(comment.status, 'replied')
  assert.match(replied.job.instruction, /Use the 2019 paper/)
  assert.equal(replied.job.context.repliesTo, comment.id)
  const second = store.propose({ jobId: job.id, type: 'comment', blockId: 'b', text: 'Fine as is.' }, 's')
  store.review(second.id, 'resolve')
  assert.equal(second.status, 'resolved')
  const next = doc(); next.content.shift()
  store.sync({ json: next, expectedRevision: 1 })
  const third = store.propose({ jobId: job.id, type: 'comment', blockId: 'a', text: 'Late.' }, 's')
  assert.equal(store.view().proposals.find(p => p.id === third.id).stale, true, 'comments on removed blocks are stale')
})
test('claim returns scoped blocks with neighbours, get_blocks reads by id, and status returns are small', () => {
  const store = new Store()
  const paragraphs = Array.from({ length: 12 }, (_, i) => ({ type: 'paragraph', attrs: { id: 'p' + i }, content: [{ type: 'text', text: 'Paragraph ' + i }] }))
  store.sync({ json: { type: 'doc', content: paragraphs }, expectedRevision: 0 })
  const job = store.enqueue({ instruction: 'x', sessionId: 's', blockIds: ['p6'] })
  const claim = store.claim(job.id, 's')
  assert.deepEqual(claim.snapshot.blocks.map(b => b.id), ['p4', 'p5', 'p6', 'p7', 'p8'])
  assert.equal(claim.snapshot.truncated, true)
  assert.equal(claim.snapshot.json, undefined)
  assert.equal(store.claim(job.id, 's', { full: true }).snapshot.blocks.length, 12)
  assert.deepEqual(store.blocks(job.id, 's', ['p0', 'p11']).blocks.map(b => b.text), ['Paragraph 0', 'Paragraph 11'])
  const status = store.status(job.id, 's', 'completed', 'done')
  assert.deepEqual(Object.keys(status).sort(), ['hint', 'jobId', 'proposals', 'status', 'updatedAt'])
  assert.match(status.hint, /comment/)
  const whole = store.enqueue({ instruction: 'y', sessionId: 's', blockIds: [] })
  assert.equal(store.claim(whole.id, 's').snapshot.blocks.length, 12, 'whole-document jobs get every block')
})
test('a cell in scope lets the agent replace the whole table, and completed jobs accept late proposals briefly', () => {
  const store = new Store()
  const table = { type: 'table', attrs: { id: 't' }, content: [{ type: 'tableRow', attrs: { id: 'r' }, content: [{ type: 'tableCell', attrs: { id: 'c' }, content: [{ type: 'paragraph', attrs: { id: 'cp' }, content: [{ type: 'text', text: 'b' }] }] }, { type: 'tableCell', attrs: { id: 'c2' }, content: [{ type: 'paragraph', attrs: { id: 'cp2' }, content: [{ type: 'text', text: 'a' }] }] }] }] }
  store.sync({ json: { type: 'doc', content: [table] }, expectedRevision: 0 })
  const job = store.enqueue({ instruction: 'sort', sessionId: 's', blockIds: ['cp'] })
  const claim = store.claim(job.id, 's')
  const t = claim.snapshot.blocks.find(b => b.id === 't')
  assert.ok(t, 'claim includes the enclosing table')
  store.status(job.id, 's', 'completed', 'oops')
  const proposal = store.propose({ jobId: job.id, type: 'replace', blockId: 't', blockRevision: t.revision, before: t.text, after: '| a | b |\n| --- | --- |', explanation: 'sorted' }, 's')
  assert.equal(proposal.blockType, 'table')
  assert.equal(store.state.jobs[0].status, 'running', 'a late proposal reopens the job')
})
test('orphaned jobs are adopted by the claiming session and reassigned to a same-name heir', () => {
  const live = new Set(['new'])
  const store = new Store(undefined, { isLiveSession: id => live.has(id) })
  store.sync({ json: doc(), expectedRevision: 0 })
  const job = store.enqueue({ instruction: 'x', sessionId: 'dead', sessionName: 'repo', blockIds: ['a'] })
  const claim = store.claim(job.id, 'new')
  assert.equal(claim.reclaimed, true)
  assert.equal(job.sessionId, 'new')
  const job2 = store.enqueue({ instruction: 'y', sessionId: 'dead', sessionName: 'repo', blockIds: [] })
  assert.deepEqual(store.orphans().map(j => j.id), [job2.id])
  store.reassign(job2, 'new')
  assert.equal(job2.sessionId, 'new')
  assert.equal(store.orphans().length, 0)
})
test('move proposals relocate a contiguous run and go stale when the run breaks', () => {
  const store = new Store()
  const ps = ['h', 'a', 'b', 'c', 'd'].map(id => ({ type: id === 'h' ? 'heading' : 'paragraph', attrs: id === 'h' ? { id, level: 2 } : { id }, content: [{ type: 'text', text: id.toUpperCase() }] }))
  store.sync({ json: { type: 'doc', content: ps }, expectedRevision: 0 })
  const job = store.enqueue({ instruction: 'move', sessionId: 's', blockIds: [] }); store.claim(job.id, 's')
  assert.throws(() => store.propose({ jobId: job.id, type: 'move', blockIds: ['a', 'c'], anchorBlockId: 'd', explanation: '' }, 's'), /contiguous/)
  const proposal = store.propose({ jobId: job.id, type: 'move', blockIds: ['h', 'a'], anchorBlockId: 'd', placement: 'after', explanation: 'heading with body' }, 's')
  assert.deepEqual(proposal.preview, ['H', 'A'])
  const result = store.review(proposal.id, 'accept')
  assert.deepEqual(result.document.json.content.map(n => n.attrs.id), ['b', 'c', 'd', 'h', 'a'])
  const again = store.propose({ jobId: job.id, type: 'move', blockIds: ['b', 'c'], anchorBlockId: 'a', explanation: '' }, 's')
  const next = structuredClone(store.state.document.json); next.content.splice(1, 0, { type: 'paragraph', attrs: { id: 'z' } })
  store.sync({ json: next, expectedRevision: store.state.document.revision })
  assert.equal(store.view().proposals.find(p => p.id === again.id).stale, true)
})
test('delete works on empty paragraphs and on tables without content validation', () => {
  const store = new Store()
  const table = { type: 'table', attrs: { id: 't' }, content: [{ type: 'tableRow', attrs: { id: 'r' }, content: [{ type: 'tableHeader', attrs: { id: 'c' }, content: [{ type: 'paragraph', attrs: { id: 'cp' }, content: [{ type: 'text', text: 'x' }] }] }] }] }
  store.sync({ json: { type: 'doc', content: [{ type: 'paragraph', attrs: { id: 'empty' } }, table, { type: 'paragraph', attrs: { id: 'keep' }, content: [{ type: 'text', text: 'Keep' }] }] }, expectedRevision: 0 })
  const job = store.enqueue({ instruction: 'tidy', sessionId: 's', blockIds: [] }); store.claim(job.id, 's')
  const empty = job.snapshot.blocks.find(b => b.id === 'empty'), tbl = job.snapshot.blocks.find(b => b.id === 't')
  assert.equal(empty.text, '')
  const p1 = store.propose({ jobId: job.id, type: 'delete', blockId: 'empty', blockRevision: empty.revision, before: '' }, 's')
  const p2 = store.propose({ jobId: job.id, type: 'delete', blockId: 't', blockRevision: tbl.revision }, 's')
  assert.throws(() => store.propose({ jobId: job.id, type: 'delete', blockId: 'keep', blockRevision: 'stale' }, 's'), /blockRevision/)
  assert.equal(store.review(p1.id, 'accept').removed, true)
  const result = store.review(p2.id, 'accept')
  assert.equal(result.removed, true)
  assert.deepEqual(result.document.json.content.map(n => n.attrs.id), ['keep'])
})
test('orphaned jobs nobody adopts expire as abandoned, including needs_permission', () => {
  const store = new Store(undefined, { isLiveSession: () => false })
  store.sync({ json: doc(), expectedRevision: 0 })
  const job = store.enqueue({ instruction: 'x', sessionId: 'dead', sessionName: 'repo', blockIds: ['a'] })
  job.status = 'needs_permission'; job.createdAt = Date.now() - 11 * 60 * 1000
  store.expireOrphans()
  assert.equal(job.status, 'abandoned')
  assert.match(job.message, /permission/)
  const fresh = store.enqueue({ instruction: 'y', sessionId: 'dead', sessionName: 'repo', blockIds: [] })
  store.expireOrphans()
  assert.equal(fresh.status, 'queued', 'recent orphans wait for an heir')
})
test('command scope is advisory; proofread scope is enforced', () => {
  const { store, job } = setup()
  const b = job.snapshot.blocks.find(x => x.id === 'b')
  const outside = store.propose({ jobId: job.id, blockId: 'b', blockRevision: b.revision, before: b.text, after: 'Changed elsewhere', explanation: 'needed' }, 's')
  assert.equal(outside.blockId, 'b')
  const pr = store.enqueue({ instruction: 'Proofread', sessionId: 's', blockIds: ['a'], kind: 'proofread' }); store.claim(pr.id, 's')
  assert.throws(() => store.propose({ jobId: pr.id, blockId: 'b', blockRevision: b.revision, before: b.text, after: 'Nope' }, 's'), /scope/)
})
test('replace_text batches a document-wide rename into one proposal and skips blocks that changed', () => {
  const store = new Store()
  const ps = ['x', 'y', 'z'].map(id => ({ type: 'paragraph', attrs: { id }, content: [{ type: 'text', text: `The Widget team ships widgets (${id}).` }] }))
  store.sync({ json: { type: 'doc', content: ps }, expectedRevision: 0 })
  const job = store.enqueue({ instruction: 'rename', sessionId: 's', blockIds: ['x'] }); store.claim(job.id, 's')
  assert.throws(() => store.propose({ jobId: job.id, type: 'replace_text', find: 'Gadget', replace: 'Gizmo' }, 's'), /does not occur/)
  const p = store.propose({ jobId: job.id, type: 'replace_text', find: 'widget', replace: 'gizmo', caseSensitive: false, explanation: 'rename' }, 's')
  assert.equal(p.edits.length, 3)
  assert.equal(p.count, 6)
  assert.equal(p.edits[0].after, 'The gizmo team ships gizmos (x).')
  const next = structuredClone(store.state.document.json); next.content[2].content[0].text = 'Rewritten by the writer.'
  store.sync({ json: next, expectedRevision: 1 })
  assert.equal(store.view().proposals[0].stale, false, 'still applies while at least one block is intact')
  const result = store.review(p.id, 'accept')
  assert.equal(result.applied.length, 2); assert.deepEqual(result.skipped, ['z'])
  assert.equal(store.snapshot().blocks[0].text, 'The gizmo team ships gizmos (x).')
  assert.equal(store.snapshot().blocks[2].text, 'Rewritten by the writer.')
})
